### ISSUE TITLE
Fix Broken Integration Tests added by Rowley

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker7#22]

**Comment by rowleya** [comment]
Happy to do - which tests are broken?

**Comment by Christian-B** [comment]
What a poor ticket!

Need to run all to find what is refered to here. Ooops!

**Comment by Christian-B** [comment]
Also:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/tests_for_routing_provenance_validity/link_failure/link_test.py

**Comment by rowleya** [comment]
I can't see what the tests in "tests_for_routing_provenance_validity" are actually checking.  I would suggest this folder is deleted (I brought it from sPyNNakerExternalDevicesPlugin but that doesn't help work out what they are for).  Note the link_test.py above works for me - it might depend on having a certain board with a valid spiNNaker link on it...

**Comment by Christian-B** [comment]
fixed spike_io_multi_run

fixed: test_for_live_packet_gather

**Comment by Christian-B** [comment]
Not done:
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/test_for_reverse_ip_tag_source

These are currently just commented out as BROKEN!

**Comment by Christian-B** [comment]
TODO:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_for_stdp/test_multiple_stdp_mechs_on_same_neuron.py

**Comment by Christian-B** [comment]
TODO:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_provenance_when_not_finished/test_provenance_when_not_started.py

Fails

**Comment by Christian-B** [comment]
TODO:
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/tests_for_sata_connectors

**Comment by Christian-B** [comment]
TODO:
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/tests_for_spinnaker_link_connectors

**Comment by Christian-B** [comment]
FAILS:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/tests_of_current_calculation/test_cond_vs_current_vs_izk.py

**Comment by Christian-B** [comment]
TODO:
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/va_bench_mark_tests

possible duplicate of
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/test_0_1_time_steps/test_va_bench_mark_tests

**Comment by andrewgait** [comment]
Started looking at and fixing some of these in https://github.com/SpiNNakerManchester/sPyNNaker7/pull/29

**Comment by andrewgait** [comment]
Added comments above to those which I have dealt with; there are a few left over still.  It's probably worth going through the equivalents in sPyNNaker8's integration tests as well to check they're working...

**Comment by andrewgait** [comment]
Everything done now (see https://github.com/SpiNNakerManchester/sPyNNaker7/pull/30) apart from https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/test_for_reverse_ip_tag_source

**Comment by rowleya** [comment]
I think these tests are mostly covered by the spike_io.py script - would be nice to know why they don't work, but it might simply be that they are so out of date that they are not worth fixing

**Comment by andrewgait** [comment]
It looks like it.  This one covers much of the same ground: https://github.com/SpiNNakerManchester/sPyNNaker7/blob/test_cleanup/p7_integration_tests/test_various/test_spike_io_multi_run.py - the only extra thing each of these scripts seem to be doing is adding different parameters to the cell_params_spike_injector; there's also a host_based_injector.py file in each directory that isn't being used.  

(The scripts aren't "working" at present because no live spikes connection is set up in them to send or receive spikes; it would be possible to update them to do this, but then all we would be testing differently from the above test is any changes to the variables in cell_params_spike_injector...)

**Comment by rowleya** [comment]
I think that all of these scripts have a host_based_injector_tester.py script along with them.  From memory, these were created to be run alongside the script to do the injection part (which I think these tests are all about).

On that basis, my opinion is to delete the tests - I am pretty sure we made the spike_io.py script based on those but so that it could be self contained.

**Comment by andrewgait** [comment]
OK, done - in that case https://github.com/SpiNNakerManchester/sPyNNaker7/pull/30 and https://github.com/SpiNNakerManchester/sPyNNaker8/pull/51 are both ready for review.

**Comment by rowleya** [comment]
Done!
